name: EAS Submit
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_KEY }}" >> .env.development
          echo "VAR_NUMBER=${{ secrets.VAR_NUMBER }}" >> .env.development
          echo "VAR_BOOL=${{ secrets.VAR_BOOL }}" >> .env.development
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.development
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas submit -p ios --latest --non-interactive
